---
# DESCRIPTION
# Apply windows updates

- name: Power on VM and perform Windows update via Powershell
  hosts: windows
  become: no
  gather_facts: no
  vars:
    ansible_user: "Administrador"
    ansible_password: "w1N0p€r2025!"
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_retries: 3
    ansible_shell_type: powershell
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    vm_name: "01 - LAB - GAM" 
    
  tasks: 
    - name: Power on the VM using PowerShell
      ansible.builtin.shell: |
        Start-VM -Name "{{ vm_name }}"
      args:
        executable: powershell.exe

    - name: Wait for VM to become available
      ansible.builtin.wait_for:
        host: "{{ 10.1.21.24 }}"
        port: 5985
        timeout: 300

- name: Prepare and Update Windows VM via PowerShell
  hosts: windows_vm
  tasks:
    - name: Set TLS 1.2 as Security Protocol
      ansible.windows.win_powershell:
        command: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
        
    - name: Set Execution Policy to RemoteSigned
      ansible.windows.win_powershell:
        command: 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force'

    - name: Set Execution Policy to Unrestricted
      ansible.windows.win_powershell:
        command: 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force'

    - name: Install PSWindowsUpdate Module
      ansible.windows.win_powershell:
        command: 'Install-Module -Name PSWindowsUpdate -Force -AllowClobber'

    - name: Add Microsoft Update Service
      ansible.windows.win_powershell:
        command: 'Add-WUServiceManager -MicrosoftUpdate -Force'

    - name: Run Windows Update via PowerShell
      ansible.windows.win_powershell:
        command: Install-WindowsUpdate -AcceptAll -AutoReboot
