---
- hosts: all
  gather_facts: no
  tasks:
  - name: Windows Update Via Powershell
   ansible.windows.win_powershell:
   script: | 
   Install-WindowsUpdate
   executable: pwsh.exe
   arguments:
    - -ExecutionPolicy
    - ByPass
