---
- name: Wake up VM and perform Windows update via Powershell
  hosts: windows
  become: no
  vars:
    vm_name: "{{ vm_name | default('default_vm_name') }}"  # Nombre de la VM, puede ser pasado como variable
    hyperv_host_ip: "10.1.21.20"  # IP del host Hyper-V
    ansible_winrm_port: 5985
  tasks:
    - name: Ensure the VM is started on Hyper-V
      win_shell: |
        $vm = Get-VM -Name "{{ vm_name }}"
        if ($vm.State -eq 'Off') {
            Start-VM -Name "{{ vm_name }}"
            Start-Sleep -Seconds 30 # Optional sleep to give the VM time to start
        }
      run_once: yes
      delegate_to: "{{ hyperv_host_ip }}"

    - name: Wait for the VM to become reachable
      wait_for:
        host: "{{ ansible_host }}"
        port: 5986  # WinRM port, or use 3389 for RDP, or 22 for SSH
        delay: 10
        timeout: 300
      delegate_to: localhost

    - name: Perform Windows Update via PowerShell
      ansible.windows.win_powershell:
        command: |
          Install-WindowsUpdate -AcceptAll -AutoReboot
